### ISSUE TITLE
Please don't use message/rfc822 with Intent.ACTION_SEND

### ISSUE THREAD

**Issue by cketti** [theyann/oneclickonemail#2]
Using `message/rfc822` as type for an `ACTION_SEND` intent will only narrow the choice of apps because email clients (like many other types of apps, e.g. file managers) include an intent filter for `*/*`.
The documentation also states that you should use `text/plain` when using `EXTRA_TEXT`.

For this app you probably want to use `ACTION_SENDTO` with a [mailto-URI](https://tools.ietf.org/html/rfc6068). You then have to encode the text and subject in the URI, e.g. 
`mailto:jane@example.org?subject=Test&body=Hello%20there`

If you still want to use `ACTION_SEND` please consider using my library [ShareIntentBuilder](https://github.com/cketti/ShareIntentBuilder) that tries very hard not to let users create share intents that are not properly formatted according to the official documentation.

**Comment by theyann** [comment]
Hello cketti, thank you very much for your comment.

I know that this is not the best way, I actually explain this in the blog post. 
The reason I use this is because is to be able to narrow the list but still be able to use multiple recipients. 
Using a mailto URI does not guarantee this functionality.

But again, thanks a bunch for your comment.

**Comment by cketti** [comment]
A mailto URI allows you to specify multiple addresses. Have you encountered a mail client that doesn't support that?

**Comment by theyann** [comment]
You are right, I should have read the official RFC. Indeed you can officially specify multiple recipients in a mailto. I was mislead by [this article](http://www.sightspecific.com/~mosh/www_faq/multrec.html), I should have gone deeper.
I will fix this, thank you very much :)
